%let name=livskv10;
%let gpath=https://raw.githubusercontent.com/KarlBangChristensen/statistikbanken/main;
filename gh url "&gpath/&name.%20data.sas";
%include gh;
*;
%let path=C:\Users\karlc\Desktop\statistikbanken;
%let path=C:\Users\pzs913;
%let name=livskv10;
libname &name "&path\&name";
proc copy in=work out=&name memtype=data;
	select codes codes_with_formats formats values;
run;
*;
proc sort data=&name..codes_with_formats;
	by v2 v3 v5;
run;
data &name..codes_with_formats;
	set &name..codes_with_formats;
	RegSj='Andre Regioner';
	if V6 in ('253','259','265','269','336','350') then do; RegSj='RegSj'; end; /* SUH */
	if V6 in ('370','306','316','320','326','329','330','340') then do; RegSj='RegSj'; end; /* NSR_H */
	if V6 in ('360','376','390') then do; RegSj='RegSj'; end; /* NFS */
	item=V2;
run;

proc freq data=&name..codes_with_formats noprint;
	where V4 in ('S82','S83','S84');
	table V4*RegSj / outpct out=table(drop=count percent pct_row);
	weight value;
	by v2 v3 v5;
run;
*;
data table;
	set table;
	if V4='S82' then V4_short='Lav';
	if V4='S83' then V4_short='Mid';
	if V4='S84' then V4_short='Høj';
run;
options printerpath=gif animation=start animduration=1 animloop=no noanimoverlay;
ods printer file="&path\&name..gif";
ods graphics / height=500px width=800px;
options nobyline;
title ;
%macro plot(item, label);
	title "&label";
	proc sgpanel data=table;
		where V3='K' and V2="&item";
		panelby V5 / columns=1 rows=6 noheader;
		hbar RegSj / response=pct_col stat=mean group=V4_short grouporder=data;
		keylegend / title=' ' noborder;
		colaxis valueattrs=(size=14) label=' ';
		rowaxis display=(/*novalues*/ noline noticks) labelattrs=(size=14) label='aldersgrupper';
	run;
%mend plot;
%plot(item=S28, label=Tillid til politikerne i Folketinget?);
%plot(item=S29, label=Tillid til lokalpolitikerne i din kommune?);
%plot(item=S30, label=Tillid til at du kan få den bedst mulige behandling fra det offentlige hvis du bliver alvorligt syg?);
%plot(item=S31, label=Tillid til at du kan få den nødvendige hjælp og service fra din kommune når du har brug for det?);
ods printer close;
*;
options printerpath=gif animation=start animduration=1 animloop=no noanimoverlay;
ods printer file="&path\&name._2.gif";
ods graphics / height=500px width=800px;
options nobyline;
title "Tillid til at du kan få et (nyt) job der passer til din uddannelse?";
	proc sgpanel data=table;
		where V3='K' and V2="S32";
		panelby V5 / columns=1 rows=5 noheader;
		hbar RegSj / response=pct_col stat=mean group=V4_short grouporder=data;
		keylegend / title=' ' noborder;
		colaxis valueattrs=(size=14) label=' ';
		rowaxis display=(/*novalues*/ noline noticks) labelattrs=(size=14) label='aldersgrupper';
	run;
ods printer close;
